### ISSUE TITLE
About differentiable_robot_model in setup.py

### ISSUE THREAD

**Issue by lewis-101** [SamsungLabs/RAMP#1]
May I ask if this differentiable_robot_model come from Meta Research

**Comment by vvasilo** [comment]
Yes, this is the package we used before. However, we recently replaced it with [pytorch-kinematics](https://github.com/UM-ARM-Lab/pytorch_kinematics). I just pushed a change to [setup.py](https://github.com/SamsungLabs/RAMP/blob/main/setup.py) to reflect that change.
