### ISSUE TITLE
Some questions about Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ChaselLau666** [SamsungLabs/RAMP#2]
Thank you for your great contributions to this field！
After I configured the environment and planned to run the code python -m test_ramp_simulation --markers True --experiment 10, I encountered the following error. The specific manifestation is that the issac gym environment will crash, as shown below
![image](https://github.com/SamsungLabs/RAMP/assets/139679124/80e777c5-3f93-43a1-ab55-88edc1eef183)
![image](https://github.com/SamsungLabs/RAMP/assets/139679124/cd1279e9-e0a8-4a6c-9187-8eba8eb555b0)

**Comment by vvasilo** [comment]
Thank you for trying out RAMP! Yes, this is a well-known issue. Could you try the following before launching `test_ramp_simulation` and see if it works?

`export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`

**Comment by ChaselLau666** [comment]
Thanks for your help this solved my problem
