### ISSUE TITLE
Dimension mismatch in _get_mesh_control_points

### ISSUE THREAD

**Issue by KehanLong** [SamsungLabs/RAMP#3]
Thank you for the great project. 
When I try to reproduce the demo for your project, it seems that there is an error when calling the torch.forward_kinematics in _get_mesh_control_points method. The details are in the attached figure. Could you please help with that? Is that a problem of appending the gripper state? 

This is tested with pytorch.kinematics 0.6.1
![Screenshot from 2024-03-07 14-53-27](https://github.com/SamsungLabs/RAMP/assets/54189362/13731491-29e2-4b71-9068-fd3434ad77ef)

**Comment by yhykid** [comment]
Hi,bro,I have met the same problem.And I have tried a lot  solving it and finally I fixed it.
I supposed you can try to input the command" pip install pytorch.kinematics==0.6.0 " .
